# Decompiles the Slay the Spire 2 game DLL using ilspycmd.
# Usage: pwsh util/decompile-sts2.ps1
#
# Requires ilspycmd to be installed:
#   dotnet tool install -g ilspycmd

param(
    [string]$Sts2Dll
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$OutputDir = Join-Path (Join-Path $ProjectRoot "decompiled") "sts2"

# Auto-detect the DLL path from common Steam locations if not provided
if (-not $Sts2Dll) {
    $candidates = @(
        "$env:ProgramFiles (x86)\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll",
        "C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll",
        "D:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) {
            $Sts2Dll = $c
            break
        }
    }
    if (-not $Sts2Dll) {
        Write-Error "Could not find sts2.dll. Pass the path explicitly: pwsh util/decompile-sts2.ps1 -Sts2Dll <path>"
        exit 1
    }
}

Write-Host "Source DLL : $Sts2Dll"
Write-Host "Output dir : $OutputDir"

# Clean existing decompiled output (preserve .uid files are regenerated by megadot)
if (Test-Path $OutputDir) {
    Write-Host "Removing old decompiled source..."
    Remove-Item -Recurse -Force $OutputDir
}

Write-Host "Decompiling..."
ilspycmd -p -o $OutputDir $Sts2Dll

if ($LASTEXITCODE -ne 0) {
    Write-Error "ilspycmd failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
}

# Remove the .csproj that ilspycmd generates (we don't need it)
Get-ChildItem -Path $OutputDir -Filter "*.csproj" | Remove-Item -Force

Write-Host "Done. Decompiled source is in $OutputDir"
